/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_parking_PlateProc */

#ifndef _Included_com_parking_PlateProc
#define _Included_com_parking_PlateProc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_parking_PlateProc
 * Method:    plateProc
 * Signature: ([III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_parking_PlateProc_plateProc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
